server:
  port: 8888

spring:
  application:
    name: dynamic-tp-zookeeper-demo
  dynamic:
    tp:
      config-type: json
      zookeeper:
        config-version: 1.0.0
        zk-connect-str: 127.0.0.1:2181
        root-node: /configserver/dev
        node: dynamic-tp-zookeeper-demo   # json 用到
        config-key: dynamic-tp-zookeeper-demo-json

# 开启 SpringBoot Actuator Endpoint 暴露出DynamicTp指标接口
# 开启 prometheus 指标采集端点
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'   # 测试使用，线上不要用*，按需开启